PetHolaKingdom/Controllers/CoursePageController.cs
using PagedList;
using PetHolaKingdom.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetHolaKingdom.Controllers
{
    public class CoursePageController : Controller
    {
        // GET: CoursePage
        ICourse course=new Course();
        ILesson lesson=new Lesson();
        public ActionResult Index(int Id, int page=1, int pageSize= 9, string keysearch="")
        {
            ViewBag.KeySearch = keysearch;
            return View(course.GetCoursePageList(Id,keysearch).ToPagedList(page, pageSize));
        }
        [Route("CoursePage/Detail/{id?}")]
        public ActionResult Detail(int Id, int page = 1, int pageSize = 9, string keysearch = "")
        {

            ViewBag.Description = course.GetCourseDetail(Id).Description;
            ViewBag.Name = course.GetCourseDetail(Id).Name;
            ViewBag.Image = course.GetCourseDetail(Id).Image;
            return View(lesson.GetLessonPageList(Id, keysearch).ToPagedList(page, pageSize));
        }
    }
}

PetHolaKingdom/Views/CoursePage/Detail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IPagedList<PetHolaKingdom.Helpers.LessonViewPage>
@using PagedList.Mvc;
@using PagedList;
@using Microsoft.AspNet.Identity;
<div class="container mt-30">
    <h2>@ViewBag.Name</h2>
    <img src="@ViewBag.Image" class="img-responsive" style="width:200px;height:200px;">
    <div>
        @Html.Raw(ViewBag.Description);
    </div>
    @using (Html.BeginForm("Detail", "CoursePage", FormMethod.Get))
    {
        <input type="text" name="keysearch" value="@ViewBag.KeySearch" placeholder="Nhập từ khoá tìm kiếm..." style=" width: 50%; margin-bottom: 20px; height: 46px;" />
        <input class="btn btn-primary" type="submit" name="submit" value="Tìm kiêm" />

        <div class="btn-group dropup">
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mức độ bài học
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
            </div>
        </div>
    }
    <!-- Example split danger button -->

    <ul class="row">
        @foreach (var item in Model)
        {
            <li class="col-sm-3">
                <div class="inner">
                    <figure>
                        <a href="">
                            <img src="@item.Image" class="img-responsive" style="width: 250px; height: 180px;">
                        </a>
                        <figcaption>
                            <div class="cnt-block">
                                <h3>@item.Name</h3>
                                @{if (item.LevelId == 1)
                                    {
                                        <a class="text-success">@item.LevelInfo</a>
                                    }
                                    else if (item.LevelId == 2)
                                    {
                                        <a class="text-warning">@item.LevelInfo</a>
                                    }
                                    else if (item.LevelId == 3)
                                    {
                                        <a class="text-danger">@item.LevelInfo</a>
                                    }
                                    else if (item.LevelId == 4)
                                    {
                                        <a class="text-dark">@item.LevelInfo</a>
                                    }

                                }


                                <div class="bottom-block clearfix">
                                    <div class="comment">
                                        <div class="icon"><span class="icon-chat-icon"></span></div>
                                        @{

                                            if (String.IsNullOrEmpty(User.Identity.Name))
                                            {

                                                <span>Đăng nhập để xem chi tiết khóa học</span>
                                                <br/>
                                                <a href="/Login/Index">
                                                    Đăng nhập ngay
                                                </a>
                                            }
                                            else
                                            {
                                                <a href="">Chưa đăng ký</a>
                                            }
                                        }

                                    </div>
                                </div>
                            </div>
                        </figcaption>
                    </figure>
                </div>
            </li>
        }

    </ul>
    @Html.PagedListPager(Model, page => Url.Action("Detail", "CoursePage", new { page, @keysearch = @ViewBag.KeySearch }))
</div>

<style>
    .inner:hover {
        box-shadow: 10px 10px 5px #aaaaaa !important;
    }

    .news-events figure {
        position: initial;
    }

    .news-events ul li .cnt-block {
        display: block;
        padding: 10px 30px 0px 30px;
        background: #fff;
        position: relative;
    }

    .news-events figcaption {
        position: relative;
        top: 0;
        left: 0;
    }

    h3 {
        text-transform: unset;
    }
</style>

PetHolaKingdom/Views/CoursePage/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IPagedList<PetHolaKingdom.Models.Cours>
@using PagedList.Mvc;
@using PagedList;


<div class="news-events padding-lg">
    <div class="container mb-4">
        @using (Html.BeginForm("Index", "CoursePage", FormMethod.Get))
        {
            <input type="text" name="keysearch" value="@ViewBag.KeySearch" placeholder="Nhập từ khoá tìm kiếm..." style=" width: 50%; margin-bottom: 20px; height: 46px;" />
            <input class="btn btn-primary" type="submit" name="submit" value="Tìm kiêm" />
        }
        <ul class="row">
            @foreach (var item in Model)
            {
                <li class="col-sm-3">
                    <div class="inner">
                        <figure>
                            <a href="/CoursePage/Detail/@item.id">
                                <img src="@item.Image" class="img-responsive" style="width:300px;height:300px;">
                            </a>
                            <figcaption>
                                <div class="cnt-block">
                                    <h3>@item.Name</h3>
                                    <div class="bottom-block clearfix">
                                        <div class="comment">
                                            <div class="icon"><span class="icon-chat-icon"></span></div>
                                            <a href="/CoursePage/Detail/@item.id">Go detail</a>
                                        </div>
                                    </div>
                                </div>
                            </figcaption>
                        </figure>
                    </div>
                </li>
            }

        </ul>
        @Html.PagedListPager(Model, page => Url.Action("Index", "CoursePage", new { page, @keysearch = @ViewBag.KeySearch }))
    </div>
</div>
<style>
    .inner:hover {
        box-shadow: 10px 10px 5px #aaaaaa !important;
    }

    .news-events figure {
        position: initial;
    }

    .news-events ul li .cnt-block {
        display: block;
        padding: 10px 30px 0px 30px;
        background: #fff;
        position: relative;
    }

    .news-events figcaption {
        position: relative;
        top: 0;
        left: 0;
    }
</style>