PetHolaKingdom/Models/Curriculum.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHolaKingdom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curriculum()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses { get; set; }
    }
}

PetHolaKingdom/Controllers/CurriculumController.cs
using PagedList;
using PetHolaKingdom.Models;
using PetHolaKingdom.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Curriculum = PetHolaKingdom.Repository.Curriculum;

namespace PetHolaKingdom.Controllers
{
    public class CurriculumController : Controller
    {
        // GET: Curriculum
        ICurriculum curri = new Curriculum();
        public ActionResult Index(int page = 1, int pageSize = 9, string keysearch = "")
        {
            ViewBag.KeySearch = keysearch;
            return View(curri.GetListCurriculum(keysearch).ToPagedList(page, pageSize));
        }
    }
}

PetHolaKingdom/Views/Curriculum/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IPagedList<PetHolaKingdom.Helpers.CurriculumList>
@using PagedList.Mvc;
@using PagedList;
<div class="news-events padding-lg">
    <div class="container mb-4">
        @using (Html.BeginForm("Index", "Curriculum", FormMethod.Get))
        {
            <input type="text" name="keysearch" value="@ViewBag.KeySearch" placeholder="Tìm đại cương..." style=" width: 50%; margin-bottom: 20px; height: 46px;" />
            <input class="btn btn-primary" type="submit" name="submit" value="Tìm kiêm" />
        }
        <ul class="row">
            @{

                foreach (var item in Model)

                {
                    <li class="col-sm-3">
                        <div class="inner">
                            <figure>
                                <a href="/CoursePage/Index/@item.Id">
                                    <img src="@item.Image" class="img-responsive" style="width:300px;height:300px;">
                                </a>
                                <figcaption>
                                    <div class="cnt-block">
                                        <h3>@item.Name</h3>
                                        <div class="bottom-block clearfix">
                                            <div class="comment">
                                                <div class="icon"><span class="icon-chat-icon"></span></div>
                                                <a href="/CoursePage/Index/@item.Id">View course</a>
                                            </div>
                                        </div>
                                    </div>
                                </figcaption>
                            </figure>
                        </div>
                    </li>
                }
            }
        </ul>
        @Html.PagedListPager(Model, page => Url.Action("Index", "Curriculum", new { page, @keysearch = @ViewBag.KeySearch }))
    </div>
</div>
<style>
    .inner:hover {
        box-shadow: 10px 10px 5px #aaaaaa !important;
    }

    .news-events figure {
        position: initial;
    }

    .news-events ul li .cnt-block {
        display: block;
        padding: 10px 30px 0px 30px;
        background: #fff;
        position: relative;
    }

    .news-events figcaption {
        position: relative;
        top: 0;
        left: 0;
    }
</style>